
import Helloworld from "@/components/helloworld";
import User from "@/components/User";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Meu primeiro site em React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Olá, mundo! Meu primeiro site em React!</h1>
      {/* Comentário no JSX */}
      {/* Importando o primeiro componente */}
      <Helloworld />
      <User />
    </>
  );
}
